### ISSUE TITLE
Seems to be incompatible with Espressif RTOS 3.1

### ISSUE THREAD

**Issue by IainColledge** [paoloach/ESP8266-open-rtos#1]
When creating a new project cmake fails with:

```
CMake Error at esp8266/CMakeLists.txt:6 (add_library):
  Cannot find source file:

    C:/msys32/home/Iain/esp/ESP8266_RTOS_SDK/components/esp8266/driver/spi_interface.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at freeRTOS/CMakeLists.txt:23 (add_library):
  Cannot find source file:

    C:/msys32/home/Iain/esp/ESP8266_RTOS_SDK/components/freertos/port/esp8266/heap_5.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at esp8266/CMakeLists.txt:6 (add_library):
  No SOURCES given to target: esp8266


CMake Error at freeRTOS/CMakeLists.txt:23 (add_library):
  No SOURCES given to target: freeRTOS
```

The actual RTOS from https://github.com/espressif/ESP8266_RTOS_SDK does not seem to have these files presents, does anything need updating please?

**Comment by paoloach** [comment]
Hi Iain

Thank you for reporting the problem.
Unfortunately, I developed the plugin when the 3.0 version wans't released.

I have to handle the new version but, honestly, now I have little time.

So, please, patient.

Regards,
Paolo


,

Il giorno sab 2 feb 2019 alle ore 19:06 Iain Colledge <
notifications@github.com> ha scritto:

**Comment by IainColledge** [comment]
Thanks for the reply and what would you suggest as a workaround please, could we use an old version that you developed against?

What would be the recommended method to install that please?

**Comment by paoloach** [comment]
Hi Iain,

I developed the pluging using the  RTOS version 2.2.
 To be precise, the commit is ea34c2af21280a946ad3eaa6a88269e94fc80485
If you use that commit, you should able to use the plugin but I think that
any 2.2.x commit should be fine.

Regards,
Paolo




Il giorno dom 3 feb 2019 alle ore 19:05 Iain Colledge <
notifications@github.com> ha scritto:

**Comment by IainColledge** [comment]
I'll try it and let you know, thank you.

**Comment by paoloach** [comment]
Hi Iain,
finaly I found the time to update the plugin to the last RTOS version

Regards,
Paolo

**Comment by IainColledge** [comment]
Awesome, thanks very much and sorry I didn't get round to testing out going backwards.
