### ISSUE TITLE
I am using clion 2019.1 but getting "incompatible with current version" error message when trying to add you plugin

### ISSUE THREAD

**Issue by DanCox09** [paoloach/ESP8266-open-rtos#4]

**Comment by paoloach** [comment]
Hi DaCox09,

Thank to using my plugin.
You are right, my plugin isn't yet compatible with the 2019.1 version.

I hope to be able to  update my pluging in few days

Regards,
Paolo


Il giorno mar 2 apr 2019 alle ore 16:55 DanCox09 <notifications@github.com>
ha scritto:

**Comment by paoloach** [comment]
From version 1.4.2 the plugin is compatible also with cliion 2019.1,

Ragards,
Paolo
